// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgmWf-B8Xw2wCkAgKnl2VVJbjFuUwK_k',
    appId: '1:749026649146:web:213f23f06b7c24a33b8103',
    messagingSenderId: '749026649146',
    projectId: 'ostad-batcth-9',
    authDomain: 'ostad-batcth-9.firebaseapp.com',
    storageBucket: 'ostad-batcth-9.firebasestorage.app',
    measurementId: 'G-52R5WGRNWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ryb9-HrcBbyKEFsNx8NVrzzGwiyIM9s',
    appId: '1:749026649146:android:e84a36e28fe508a83b8103',
    messagingSenderId: '749026649146',
    projectId: 'ostad-batcth-9',
    storageBucket: 'ostad-batcth-9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL4bs-0rWTD19hGerYesRbAoFIVnvN1Ws',
    appId: '1:749026649146:ios:78d10ee5ae8155d73b8103',
    messagingSenderId: '749026649146',
    projectId: 'ostad-batcth-9',
    storageBucket: 'ostad-batcth-9.firebasestorage.app',
    iosBundleId: 'com.example.eeCommercre',
  );
}
